import type { SettingsPageContentProps } from "./PageContentProps";
import {
  readSettingsPageContentActions,
  type SettingsPageContentBuilderOptions,
} from "./PageContentBuilder";

export function useSettingsPageContentProps(
  input: SettingsPageContentBuilderOptions,
): SettingsPageContentProps {
  return {
    addConnectionDefinitions: input.addConnectionDefinitions,
    addConnectionTargetAgentId: input.addConnectionTargetAgentId,
    canConfigureAgent: input.canConfigureAgent,
    credentialStorageMode: input.credentialStorageMode,
    credentialStorageState: input.credentialStorageState,
    defaultOpenAiAuthJsonPath: input.defaultOpenAiAuthJsonPath,
    definitions: input.definitions,
    historyState: input.historyState,
    isCredentialStorageModeLocked: input.credentialStorageModeState.isLocked,
    isCredentialStorageModeMixed: input.credentialStorageModeState.isMixed,
    isCredentialPortabilityBusy: input.isCredentialPortabilityBusy,
    isLoadedStatusEntryDisplay: input.isLoadedStatusEntryDisplay,
    isLoadedNotificationMute: input.isLoadedNotificationMute,
    isLoadingNotificationHistory: input.isLoadingNotificationHistory,
    isMarkingNotificationHistoryRead: input.isMarkingNotificationHistoryRead,
    isResetting: input.isResetting,
    isSavingStatusEntryDisplay: input.isSavingStatusEntryDisplay,
    isSavingNotificationMute: input.isSavingNotificationMute,
    isSavingProfileFeature: input.isSavingProfileFeature,
    language: input.language,
    statusEntryDisplayMode: input.statusEntryDisplayMode,
    notificationHistoryConnections: input.notificationHistoryConnections,
    notificationHistoryFilter: input.notificationHistoryFilter,
    notificationHistoryState: input.notificationHistoryState,
    notificationsMuted: input.notificationsMuted,
    preferences: input.preferences,
    profileError: input.profileError,
    profileFeatureEnabled: input.profileFeatureEnabled,
    profiles: input.profiles,
    releaseInfo: input.releaseInfo,
    savedConnectionCount: input.settingsState.advanced.savedConnectionCount,
    selectedAgentDetailId: input.selectedAgentDetailId,
    selectedAgentDetailTab: input.selectedAgentDetailTab,
    selectedConnectionContextAgent: input.selectedConnectionContextAgent,
    selectedConnectionId: input.selectedConnectionId,
    selectedProfileId: input.selectedProfileId,
    settingsState: input.settingsState,
    showProfiles: input.showProfiles,
    showQuickSetupNav: input.showQuickSetupNav,
    t: input.t,
    visiblePage: input.visiblePage,
    ...readSettingsPageContentActions(input),
  };
}
