import { lstatSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const PROFILE_BLOCK_START = "# BEGIN nile-switcher managed environment";
const PROFILE_BLOCK_END = "# END nile-switcher managed environment";

type PosixProfile = {
  path: string;
};

export class DesktopShellEnvironment {
  private readonly indexPath: string;
  private readonly posixScriptPath: string;
  private readonly fishScriptPath: string;
  private readonly posixProfiles: PosixProfile[];

  constructor(
    private readonly options: {
      serviceName?: string;
      homeDir?: string;
      indexPath?: string;
      posixScriptPath?: string;
      fishScriptPath?: string;
      posixProfilePaths?: string[];
      securityCommandPath?: string;
    } = {},
  ) {
    const homeDir = options.homeDir ?? homedir();
    this.indexPath = options.indexPath ?? join(homeDir, ".nile-switcher", "environment", "managed-keys.json");
    this.posixScriptPath =
      options.posixScriptPath ?? join(homeDir, ".nile-switcher", "environment", "managed.sh");
    this.fishScriptPath =
      options.fishScriptPath ?? join(homeDir, ".config", "fish", "conf.d", "nile-switcher-managed.fish");
    this.posixProfiles = (options.posixProfilePaths ?? readDefaultPosixProfiles(homeDir)).map((path) => ({ path }));
  }

  ensure(envKey: string): void {
    const next = new Set(this.readManagedKeys());
    next.add(this.normalizeEnvKey(envKey));
    this.writeState([...next].sort());
  }

  sync(envKeys: string[]): void {
    const keys = [...new Set(envKeys.map((envKey) => this.normalizeEnvKey(envKey)))].sort();
    this.writeState(keys);
  }

  remove(envKey: string): void {
    const normalizedEnvKey = this.normalizeEnvKey(envKey);
    const next = this.readManagedKeys().filter((key) => key !== normalizedEnvKey);
    this.writeState(next);
  }

  private writeState(keys: string[]): void {
    if (keys.length === 0) {
      this.removeScripts();
      this.removeProfileBlocks();
      return;
    }

    this.writeIndex(keys);
    this.writePosixScript(keys);
    this.writeFishScript(keys);
    this.ensureProfileBlocks();
  }

  private writeIndex(keys: string[]): void {
    this.writeTextFile(this.indexPath, `${JSON.stringify(keys, null, 2)}\n`);
  }

  private writePosixScript(keys: string[]): void {
    this.writeTextFile(this.posixScriptPath, this.buildPosixScript(keys));
  }

  private writeFishScript(keys: string[]): void {
    this.writeTextFile(this.fishScriptPath, this.buildFishScript(keys));
  }

  private readManagedKeys(): string[] {
    try {
      const parsed = JSON.parse(readFileSync(this.indexPath, "utf8")) as unknown;
      if (!Array.isArray(parsed)) {
        return [];
      }
      return parsed
        .filter((value): value is string => typeof value === "string")
        .map((value) => value.trim())
        .filter((value) => /^[A-Z_][A-Z0-9_]*$/.test(value));
    } catch {
      return [];
    }
  }

  private buildPosixScript(keys: string[]): string {
    const securityCommandPath = JSON.stringify(this.options.securityCommandPath ?? "/usr/bin/security");
    const serviceName = JSON.stringify(this.options.serviceName ?? "nile.switcher.environment");
    const lines = [
      "# Generated by Nile. Reads managed environment keys from macOS Keychain.",
      ...keys.flatMap((envKey) => [
        `if _nile_switcher_env_value="$(${securityCommandPath} find-generic-password -w -a ${JSON.stringify(envKey)} -s ${serviceName} 2>/dev/null)"; then`,
        `  export ${envKey}="$_nile_switcher_env_value"`,
        "else",
        `  unset ${envKey}`,
        "fi",
      ]),
      "unset _nile_switcher_env_value",
      "",
    ];
    return `${lines.join("\n")}`;
  }

  private buildFishScript(keys: string[]): string {
    const securityCommandPath = escapeSingleQuotes(this.options.securityCommandPath ?? "/usr/bin/security");
    const serviceName = escapeSingleQuotes(this.options.serviceName ?? "nile.switcher.environment");
    const lines = [
      "# Generated by Nile. Reads managed environment keys from macOS Keychain.",
      ...keys.flatMap((envKey) => [
        `set -l _nile_switcher_env_value (${securityCommandPath} find-generic-password -w -a '${escapeSingleQuotes(envKey)}' -s '${serviceName}' ^/dev/null 2>/dev/null)`,
        "if test $status -eq 0",
        `  set -gx ${envKey} "$_nile_switcher_env_value"`,
        "else",
        `  set -e ${envKey}`,
        "end",
      ]),
      "set -e _nile_switcher_env_value",
      "",
    ];
    return `${lines.join("\n")}`;
  }

  private ensureProfileBlocks(): void {
    for (const profile of this.posixProfiles) {
      this.assertSafeFileTarget(profile.path);
      const current = this.readFile(profile.path);
      const next = this.replaceManagedBlock(current, this.buildPosixProfileBlock());
      if (next !== current) {
        this.writeTextFile(profile.path, next);
      }
    }
  }

  private removeProfileBlocks(): void {
    for (const profile of this.posixProfiles) {
      this.assertSafeFileTarget(profile.path);
      const current = this.readFile(profile.path);
      const next = this.replaceManagedBlock(current, "");
      if (next === current) {
        continue;
      }
      this.writeTextFile(profile.path, next);
    }
  }

  private buildPosixProfileBlock(): string {
    const scriptPath = escapeDoubleQuotes(this.posixScriptPath);
    return [
      PROFILE_BLOCK_START,
      'if [ -z "${NILE_SWITCHER_MANAGED_ENV_LOADED:-}" ]; then',
      "  export NILE_SWITCHER_MANAGED_ENV_LOADED=1",
      `  if [ -f "${scriptPath}" ]; then`,
      `    . "${scriptPath}"`,
      "  fi",
      "fi",
      PROFILE_BLOCK_END,
    ].join("\n");
  }

  private replaceManagedBlock(current: string, replacement: string): string {
    const blockPattern = new RegExp(
      `${escapeRegExp(PROFILE_BLOCK_START)}[\\s\\S]*?${escapeRegExp(PROFILE_BLOCK_END)}\\n?`,
      "m",
    );
    const trimmedReplacement = replacement ? `${replacement}\n` : "";
    if (blockPattern.test(current)) {
      const next = current.replace(blockPattern, trimmedReplacement).replace(/\n{3,}/g, "\n\n");
      return replacement ? next : next.replace(/\n{2,}$/g, "\n");
    }

    if (!replacement) {
      return current;
    }

    const trimmedCurrent = current.trimEnd();
    return trimmedCurrent ? `${trimmedCurrent}\n\n${replacement}\n` : `${replacement}\n`;
  }

  private readFile(path: string): string {
    try {
      return readFileSync(path, "utf8");
    } catch {
      return "";
    }
  }

  private removeScripts(): void {
    this.removeFile(this.indexPath);
    this.removeFile(this.posixScriptPath);
    this.removeFile(this.fishScriptPath);
  }

  private normalizeEnvKey(envKey: string): string {
    const normalizedEnvKey = envKey.trim();
    if (!/^[A-Z_][A-Z0-9_]*$/.test(normalizedEnvKey)) {
      throw new Error(`Environment variable name is invalid: ${envKey}`);
    }
    return normalizedEnvKey;
  }

  private writeTextFile(path: string, content: string): void {
    this.assertSafeFileTarget(path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf8");
  }

  private removeFile(path: string): void {
    this.assertSafeFileTarget(path);
    rmSync(path, { force: true });
  }

  private assertSafeFileTarget(path: string): void {
    try {
      const stat = lstatSync(path);
      if (stat.isSymbolicLink()) {
        throw new Error(`Refusing to manage shell environment through symlinked path: ${path}`);
      }
    } catch (error) {
      if (isMissingFileError(error)) {
        return;
      }
      throw error;
    }
  }
}

function readDefaultPosixProfiles(homeDir: string): string[] {
  return [
    join(homeDir, ".zprofile"),
    join(homeDir, ".bash_profile"),
    join(homeDir, ".profile"),
  ];
}

function escapeDoubleQuotes(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function escapeSingleQuotes(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("'", "\\'");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}
